namespace CFMonitor.Enums
{
    public enum MonitorItemTypes : byte
    {
        ActiveProcess,
        CPU,
        DHCP,
        DiskSpace,
        DNS,
        FileSize,
        FolderSize,
        IMAP,
        LocalFile,
        JSON,
        LDAP,
        Memory,        
        Ping,
        POP,
        //Registry,
        REST,
        RunProcess,
        //Service,
        SMTP,
        SOAP,
        Socket,
        SQL,
        Time,
        URL
    }
}
